### ISSUE TITLE
✨ [Feature] 온보딩 페이지 만들기

### ISSUE THREAD

**Issue by Austin-Choi** [Parrotalk/Parrotalk_FE#10]
### Description

홈이 될 온보딩 페이지를 구현합니다.
상위에는 nav 바와 header용 로고, 우측에는 마이페이지가 존재합니다.
body에는 
video로 서비스를 소개하는 영상을 넣거나
서비스를 소개하는 내용을 담습니다.
영상이 끝나면 Login component로 이동합니다.

### Todo

- [x] 공용 디자인 요소 정리
- [x] 메인 레이아웃 구현
- [x] 헤더 구현
- [x] 온보딩 페이지 구현
