### ISSUE TITLE
✨ [Feature] CallScreen, ChatBox css입히기

### ISSUE THREAD

**Issue by Austin-Choi** [Parrotalk/Parrotalk_FE#13]
### Description

Figma를 참고하여 CallScreen의 세부 항목인 ChatBox css를 먼저 입히고 
CallScreen css를 작업합니다.

### Todo

- [x] CallSetting 작업 (통화 옵션 고르는거)
- [x] CallVoiceScreen 작업
- [x] CallControl 작업
- [x] CallChatScreen 작업
- [x] ChatBox 새 채팅 생기면 자동으로 아래로 내려가게 스크롤 조정
- [x] 배경색 -> 배경 이미지로 변경
