### ISSUE TITLE
✨ [Feature] EndCallScreen 구현하기

### ISSUE THREAD

**Issue by Austin-Choi** [Parrotalk/Parrotalk_FE#32]
### Description

![EndCallScreen-prototype](https://github.com/user-attachments/assets/7fda7f26-5840-451d-85ae-5e8ba4d14ec5)
피그마를 참조해서 위 화면과 기능을 EndCallScreen이라는 컴포넌트로 구현합니다.

### Todo

- [ ] CallChatScreen에 있는 CallControl 컴포넌트 디자인 참고해서 통화종료 제목 섹션 만들기
- [ ] 앵픽된 Todo 구현
- [ ] 선택항목 기록하기 버튼 기능 및 디자인 구현(누르면 /call/home으로 navigate 돼야함)
