### ISSUE TITLE
🔨 [Refactoring] 채팅 박스 구현하기(CSS X) 

### ISSUE THREAD

**Issue by Austin-Choi** [Parrotalk/Parrotalk_FE#4]
### Description

STT와 TTS 사용을 위한 ChatBox를 구현합니다.
CSS 작업은 배제하고 기본 기능부터 작업합니다.

### Todo

- [x] 채팅방에 입장했을때 with chat과 only voice 고르고 연결되게끔 작업
- [x] 한번 화면을 고르면 바꿀 수 없게 고정
- [x] 상대방의 채팅은 왼쪽에, 내 채팅은 오른쪽에 뜨게 하기
- [x] AWS Transcribe
- [x] 종료 로직 버그 해결
