### ISSUE TITLE
✨ [Feature] 서버배포 빌드 및 모니터링 파일추가

### ISSUE THREAD

**Issue by suugit** [Parrotalk/Parrotalk_FE#43]
### Description

서버 배포에 필요한 파일 작성

### Todo

- [ ] node 서버로 띄우는 빌드파일 작성
- [ ] 모니터링 패키지 추가
- [ ] 수동빌드 스크립트 작성
