### ISSUE TITLE
🔨 [Refactoring] 디자인 개선사항 적용

### ISSUE THREAD

**Issue by Austin-Choi** [Parrotalk/Parrotalk_FE#50]
### Description

1. CallChatScreen에서 로딩중 컴포넌트 헤더 아래로 가려지는거 고치기 
2. 버튼 눌렀을때 배경 진해지는거 다시 푸는 css코드 추가하기
3. CallHomeScreen에서 방생성 들어간 컴포넌트 가로로 가운데정렬 시키기
4. CallScreen에서 짜치는 alert문을 제거하고 모달로 대체합니다.

### Todo

- [x] 로딩 컴포넌트 sticky로 처리
- [x] 버튼 공통 css 수정
- [ ] CallHomeScreen에서 call-home-container 가로 center 정렬
- [x] CallScreen에서 alert문 모달로 대체
