### ISSUE TITLE
🔨 [Refactoring] roomname encoding 

### ISSUE THREAD

**Issue by Austin-Choi** [Parrotalk/Parrotalk_FE#67]
### Description

링크에 직접적으로 드러나있던 talkId를 제거하고 roomname은 encoding하고 필요시 decoding 합니다. 

### Todo

- [x] roomname encoding 함수 만들기
- [x] roomname decoding 함수 만들기
- [x] 매번 encode/decode 하는 것보다 효율적인 방법 있을지 고민하기
- [x] 변조된 링크의 경우 모달창 띄워서 홈으로 간다는 것 알리기
