### ISSUE TITLE
🔨 [Refactoring] 상대의 비정상적 통화 종료 처리

### ISSUE THREAD

**Issue by Austin-Choi** [Parrotalk/Parrotalk_FE#74]
### Description

<img width="900" alt="스크린샷 2024-12-16 오후 9 03 43" src="https://github.com/user-attachments/assets/de7e7e4c-71ca-4843-bac1-563d7749da9b" />

상대방이 방 이름을 변조해서 홈으로 나가졌거나 
들어오기 전에 나갔거나 
아예 안 들어왔는데 내가 종료해서 비정상 통화 종료거나
상대방과 내가 제대로 연결해서 통화를 하고 종료 버튼을 누르지 않은 모든 상황에 대해서 보완 로직을 작성합니다.
닉네임이 아예 빈값으로 들어오거나 profile 사진이 비었거나 다른 값으로 채워진다거나
관련 컴포넌트 : EndCallScreen, CallControl

### Todo

- [ ] 비정상 종료 정의하기
- [ ] 각 종료에 관해서 보완 로직 설계하기
- [x] 필요하면 종료 로직 손 보기
