### ISSUE TITLE
🔨 [Refactoring] ux적으로 어색한 부분 고치기 

### ISSUE THREAD

**Issue by Austin-Choi** [Parrotalk/Parrotalk_FE#79]
### Description

기능에는 문제 없지만 ux상 불편한 부분들을 수정합니다.
이후 추가

### Todo

- [x] onboarding screen에서 카카오톡 로그인 버튼 가려지는 문제 해결하기
- [x] EndCallScreen에서 null 님과의 통화 .. 수정하기
- [x] 마이페이지에서 최근 통화내역 없으면 없다고 알려주기
- [x] 방이 이미 꽉 차면 모달로 알려주고 홈으로 이동시키기 
- [x] endcallscreen에서 로그인된 상태가 아니면 통화 내용 기록하기가 아니라 홈으로 이동하기로 표시하던가 누르면 '로그인해서 통화 요약을 기록하세요' 모달 뜨게 하기
