### ISSUE TITLE
🐛 [Bug] 로그인 JWT 버그 

### ISSUE THREAD

**Issue by KimGyeongLock** [Parrotalk/Parrotalk_FE#82]
### Todo

- [x] 수신자 먼저 입장 후 발신자 입장시 로딩이 계속되는 버그 해결
- [x] peerContext에 값이 계속 남아있는 버그
- [x] access 키 만료시 갇혀버리는 버그

### Problem

1. refresh는 정상이고 access는 존재하는데 만료된 상황이라 userinfo가 없어서 마이페이지 가서 로그아웃 못하고 갇혀버린 상황
![image](https://github.com/user-attachments/assets/7d301330-1499-488a-ae32-6dd953cfd0b9)

2. 1번 사진 상황에서 access 토큰을 아예 localstorage에서 삭제했더니 동작
![image](https://github.com/user-attachments/assets/7739a5ae-3fb7-41ca-be16-4f6ac171547a)

3. EndCallScreen에서 비정상적으로 종료했을 때
![image](https://github.com/user-attachments/assets/26798b41-9f84-4937-8639-b054966d964b)

4. 둘 다 익명일때 하나는 익명으로 나오고 하나는 undefined
![image](https://github.com/user-attachments/assets/c7d58387-c9ae-4d2c-90fb-be84242aec28)
![image](https://github.com/user-attachments/assets/5c755593-b1dc-4358-a9b5-827f93b62f61)
